[package]
name = "cobalt_core"
version = "0.1.0"
edition = "2021"

[features]
# Enables more detailed performance statistics
debug_stats = []

[dependencies]
# Graphics
wgpu = "0.19.1"
winit = "0.29.10"
bytemuck = { version = "1.14.1", features = ["derive"] }
image = "0.24.8"

# Misc
serde = { version = "1.0.196", features = ["derive"] }
hashbrown = { version = "0.14.3", features = [
    "serde",
    "ahash",
], default-features = false }
pollster = "0.3.0"
thiserror = "1.0.56"
log = "0.4.20"
imstr = "0.2.0"
parking_lot = {version = "0.12.1", features = []}
ultraviolet = { version = "0.9.2", features = ["serde", "bytemuck"] }

# ECS
serde_closure = "0.3.3"

tobj = "4.0.1"
downcast = "0.11.0"

[dev-dependencies]
simple_logger = "4.3.3"
serde_yaml = "0.9.30"
rand = "0.8.5"
walkdir = "2.4.0"
