workspace = { members = ["examples/game"] }
[package]
name = "cobalt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compile-time = "0.2.0"
hashbrown = {version = "0.14.3", features = ["serde", "ahash"], default_features = false}
packed_simd = "0.3.9"
serde = {version = "1.0.193", features = ["derive"]}
serde_closure = "0.3.3"
serde_traitobject = {version = "0.2.8", features = ["serde_closure"]}

[dev-dependencies]
serde_yaml = "0.9.30"

[profile.release]
debug = true
