[package]
name = "cobalt"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
cobalt_core = { path = "cobalt_core" }
cobalt_runtime = { path = "cobalt_runtime" }

[dev-dependencies]
simple_logger = "4.3.3"

[workspace]
members = [
    # Crates
    "cobalt_core",
    "cobalt_editor",
    "cobalt_runtime",
    # Examples
    "examples/test_scene",
]
