workspace = { members = ["examples/game"] }
[package]
name = "cobalt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Graphics
wgpu = "0.19.1"
winit = "0.29.10"
bytemuck = { version = "1.14.1", features = ["derive"] }
image = "0.24.8"

# Serialization
compile-time = "0.2.0"
serde = { version = "1.0.196", features = ["derive"] }
serde_closure = "0.3.3"
serde_traitobject = { version = "0.2.8", features = ["serde_closure"] }

# Misc
crossbeam-channel = "0.5.11"
hashbrown = { version = "0.14.3", features = [
    "serde",
    "ahash",
], default-features = false }
pollster = "0.3.0"
thiserror = "1.0.56"
log = "0.4.20"
imstr = "0.2.0"
parking_lot = {version = "0.12.1", features = []}
ultraviolet = { version = "0.9.2", features = ["serde", "bytemuck"] }
log-once = "0.4.1"

[dev-dependencies]
simple_logger = "4.3.3"
serde_yaml = "0.9.30"
rand = "0.8.5"
walkdir = "2.4.0"

[profile.release]
# For profiling
debug = true
