[package]
name = "cobalt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = {version = "0.14.3", features = ["serde"], default_features = false}
packed_simd = "0.3.9"
serde = {version = "1.0.193", features = ["derive"]}

[dev-dependencies]
hecs = "0.10.4"

[profile.release]
debug = true
