[[assets]]
asset_id = "638658d1-dca0-4edb-a412-181baa9423f4"
relative_path = "logo_compressed.asset"
name = "logo_compressed"
type_name = "Texture<RGBA8UnormSrgb>"

[assets.pack]
compression = 4

[assets.timestamp]
secs_since_epoch = 1729324810
nanos_since_epoch = 367431335

[assets.extra]
mime = "image/png"

[[assets]]
asset_id = "8edcba76-4eb9-4785-84b2-effea5de57ec"
relative_path = "test.asset"
name = "test"
type_name = "Texture<RGBA8UnormSrgb>"

[assets.pack]
compression = 4

[assets.timestamp]
secs_since_epoch = 1729360691
nanos_since_epoch = 180372768

[assets.extra]
mime = "image/png"

[[assets]]
asset_id = "14d3c3e5-d1e4-4ea4-8cdb-c9e17dc6979a"
relative_path = "bunny.asset"
name = "bunny"
type_name = "Mesh"

[assets.pack]

[assets.timestamp]
secs_since_epoch = 1729405470
nanos_since_epoch = 529254513

[assets.extra]

[[assets]]
asset_id = "6de96971-4f43-4995-a51c-2f4d1b268f7e"
relative_path = "dragon.asset"
name = "dragon"
type_name = "Mesh"

[assets.pack]
compression = 3

[assets.timestamp]
secs_since_epoch = 1729407915
nanos_since_epoch = 685122023

[assets.extra]

[[assets]]
asset_id = "fd198cb2-a364-4c3b-ac7e-2ad6f3ac08aa"
relative_path = "horse.asset"
name = "horse"
type_name = "Mesh"

[assets.pack]
compression = 9

[assets.timestamp]
secs_since_epoch = 1729424695
nanos_since_epoch = 380783110

[assets.extra]

[[assets]]
asset_id = "efa3d4ec-73c4-4255-8d02-2c413deec608"
relative_path = "teapot.asset"
name = "teapot"
type_name = "Mesh"

[assets.pack]
compression = 6

[assets.timestamp]
secs_since_epoch = 1729425395
nanos_since_epoch = 497819499

[assets.extra]

[[assets]]
asset_id = "50ad798a-afe9-432a-b550-a81e81ada203"
relative_path = "beetle.asset"
name = "beetle"
type_name = "Mesh"

[assets.pack]

[assets.timestamp]
secs_since_epoch = 1729425905
nanos_since_epoch = 844178164

[assets.extra]
