[[assets]]
asset_id = "638658d1-dca0-4edb-a412-181baa9423f4"
relative_path = "logo_compressed.asset"
name = "logo_compressed"
type_name = "Texture<RGBA8UnormSrgb>"

[assets.pack]
compression = 4

[assets.timestamp]
secs_since_epoch = 1729324810
nanos_since_epoch = 367431335

[assets.extra]
mime = "image/png"

[[assets]]
asset_id = "8edcba76-4eb9-4785-84b2-effea5de57ec"
relative_path = "test.asset"
name = "test"
type_name = "Texture<RGBA8UnormSrgb>"

[assets.pack]
compression = 4

[assets.timestamp]
secs_since_epoch = 1729360691
nanos_since_epoch = 180372768

[assets.extra]
mime = "image/png"

[[assets]]
asset_id = "14d3c3e5-d1e4-4ea4-8cdb-c9e17dc6979a"
relative_path = "bunny.asset"
name = "bunny"
type_name = "Mesh"

[assets.pack]

[assets.timestamp]
secs_since_epoch = 1729405470
nanos_since_epoch = 529254513

[assets.extra]

[[assets]]
asset_id = "6de96971-4f43-4995-a51c-2f4d1b268f7e"
relative_path = "dragon.asset"
name = "dragon"
type_name = "Mesh"

[assets.pack]
compression = 3

[assets.timestamp]
secs_since_epoch = 1729407915
nanos_since_epoch = 685122023

[assets.extra]
