name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run core tests
      run: cd cobalt_core && cargo test --verbose -- --test-threads=1
    - name: Run runtime tests
      run: cd cobalt_runtime && cargo test --verbose -- --test-threads=1
    - name: Run editor tests
      run: cd cobalt_editor && cargo test --verbose -- --test-threads=1
